services:

  dev:
    image: ghcr.io/hypubdy/dev:latest
    restart: always
    container_name: dev
    command: ["fish"]
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - TERM=xterm-256color
      - TZ=Asia/Bangkok
    volumes:
      - dev_data:/var/lib/docker
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
      - ./src:/root/workspace
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # network_mode: host
    networks:
      - dev-network

  app:
    image: ghcr.io/hypubdy/dev:latest
    restart: always
    container_name: app
    command: ["fish"]
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - TERM=xterm-256color
      - TZ=Asia/Bangkok
    volumes:
      - app_data:/var/lib/docker
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
      - ./app:/root/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # network_mode: host
    networks:
      - dev-network
volumes:
  dev_data:
  app_data:
networks:
  dev-network: