services:

  dev:
    image: ghcr.io/hypubdy/dev:latest
    restart: always
    container_name: dev
    command: ["fish"]
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - TERM=xterm-256color
      - TZ=Asia/Bangkok
    volumes:
      - cursor_data:/root/.cursor
      - vscode_data:/root/.vscode
      - dev_data:/var/lib/docker
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
      - ./src:/root/workspace
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # network_mode: host
    networks:
      - dev-network

  app:
    image: ghcr.io/hypubdy/dev:latest
    restart: always
    container_name: app
    command: ["fish"]
    privileged: true
    tty: true
    stdin_open: true
    environment:
      - TERM=xterm-256color
      - TZ=Asia/Bangkok
    volumes:
      - app_data:/var/lib/docker
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
      - ./app:/root/workspace
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # network_mode: host
    networks:
      - dev-network

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - dev-network

volumes:
  cursor_data:
  vscode_data:
  dev_data:
  app_data:
networks:
  dev-network:
